[build-system]
requires = ["hatchling", 'hatch-vcs']
build-backend = 'hatchling.build'

[project]
name = 'cirrocumulus'
description = 'Bring your single-cell data to life'
readme = 'README.rst'
authors = [
    { name = 'Joshua Gould', email = 'cirrocumulus@googlegroups.com' },
]
urls.Source = 'https://github.com/lilab-bcb/cirrocumulus'
urls.Documentation = "https://cirrocumulus.readthedocs.io/"

license = { file = 'LICENSE' }
dynamic = ['version']
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    'Intended Audience :: Science/Research',
    "License :: OSI Approved :: BSD License",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: Implementation :: PyPy",
    'Topic :: Scientific/Engineering :: Bio-Informatics',
    'Topic :: Scientific/Engineering :: Visualization'
]

requires-python = '>=3.11'
dependencies = [
    "anndata",
    "CacheControl",
    "flask",
    "flask-compress",
    "fsspec",
    "gunicorn",
    "numpy",
    "pandas",
    "pymongo",
    "requests",
    "scipy",
    "zarr>=3"
]

[project.optional-dependencies]
parquet = [
    'pyarrow',
]
test = [
    'pytest',
    'scanpy',
    'mongomock',
]

[tool.hatch.build.targets.sdist]
only-include = ["cirrocumulus", "build"]

[tool.hatch.build.targets.wheel]

[tool.hatch.version]
source = 'vcs'

dev = ['pre-commit', 'isort', 'black']

[tool.ruff]
line-length = 88
target-version = "py312"
fix = true

[tool.ruff.format]
docstring-code-format = true

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F",
    # isort
    "I001", ]
ignore = []

[tool.pytest.ini_options]
python_files = 'test_*.py'
testpaths = 'tests/'
xfail_strict = true
log_format = '%(asctime)s %(levelname)s %(message)s'
log_date_format = '%Y-%m-%d %H:%M:%S'
log_cli = true
log_cli_level = 'INFO'

[project.scripts]
cirro = 'cirrocumulus.__main__:main'
